### ISSUE TITLE
Voice codes changed

### ISSUE THREAD

**Issue by nonoumasy** [jankapunkt/easy-speech#209]
**Describe the bug**
Voice codes changed. My language mapping is no longer working. It's not really an issue as I can edit my mapping, but if this keeps changing, then it might be an issue in the future.

**To Reproduce**
...

**Expected behavior**
...

**Screenshots**
This is my language mapping before.
<img width="244" alt="Screenshot 2023-10-01 at 12 42 20 AM" src="https://github.com/jankapunkt/easy-speech/assets/6312676/2926a3a6-08a8-4cd7-baab-3bcd786ff0c6">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] 117

**Smartphone (please complete the following information):**

**Additional context**
not sure why the codes would change as it's standardized by Web Speech API, doesn't it?
this is the correct mapping as of today.
<img width="212" alt="Screenshot 2023-10-01 at 12 54 15 AM" src="https://github.com/jankapunkt/easy-speech/assets/6312676/0f90962a-de3e-4fa6-9757-415c014f6854">

The voice has been updated so this is no longer an issue. Just wondering how the voices code mapping changed. Was this changed on teh Web API side or from this library?

**Comment by jankapunkt** [comment]
Hey @nonoumasy did your browsers / os update since the last check? I know for sure, that Apple made lots of changes in their TTS voices recentrly, causing lots of trouble.

Since ios 16 there are also not all voices available anymore. This is on Apple unfortunately and a system-level setting we can't really influence.

https://developer.apple.com/forums/thread/723503

https://stackoverflow.com/questions/77079506/eloquence-voices-are-speaking-extra-bs


One approach might be to create an algorithm that makes sure the voices are always sorted and filtered, based on heuristics, rather than specific voice names.

**Comment by nonoumasy** [comment]
thanks. I disabled the tts feature on iOS since safari always had issues with the web speech api. But the issue was present on desktop chrome. At the moment, the mapping seems to be ok.
